### ISSUE TITLE
ruby 2.2.0 has problem

### ISSUE THREAD

**Issue by volanja** [volanja/ansible-Gitlab#15]
https://app.wercker.com/#buildstep/5550ce373ff4b3ee380c3ee0

```
TASK: [gitlab | Initialize Database and Activate Advanced Features] *********** 
failed: [dest] => {"changed": true, "cmd": "export force=yes && bundle exec rake gitlab:setup RAILS_ENV=production", "delta": "0:00:07.942081", "end": "2015-05-11 15:56:59.871571", "rc": 1, "start": "2015-05-11 15:56:51.929490", "warnings": []}
stderr: /home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/fog-core-1.21.1/lib/fog/core/collection.rb:148: warning: circular argument reference - filters
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/fog-1.21.0/lib/fog/rackspace/mock_data.rb:43: warning: duplicated key at line 81 ignored: "name"
rake aborted!
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes.
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/execjs-2.0.2/lib/execjs/runtimes.rb:51:in `autodetect'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/execjs-2.0.2/lib/execjs.rb:5:in `<module:ExecJS>'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/execjs-2.0.2/lib/execjs.rb:4:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/coffee-script-2.2.0/lib/coffee_script.rb:1:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/coffee-script-2.2.0/lib/coffee-script.rb:1:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.2.0/gems/coffee-rails-4.0.1/lib/coffee-rails.rb:1:in `<top (required)>'
/home/git/gitlab/config/application.rb:6:in `<top (required)>'
/home/git/gitlab/Rakefile:5:in `require'
/home/git/gitlab/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

FATAL: all hosts have already failed -- aborting

```

**Comment by volanja** [comment]
link https://gitlab.com/gitlab-org/gitlab-ce/issues/930

use Ruby 2.1.x
